apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kadkcno6g-python 
  janus-idp.io/tekton: kadkcno6g-python
  backstage.io/kubernetes-id: kadkcno6g-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kadkcno6g-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml